### PR TITLE
feat: add userscript output support

### PR DESCRIPTION
**Pull request by dylanarmstrong**
## Description
Add ability to output [userscript](https://github.com/quoid/userscripts) for Safari support.

## DuckDuckGo
Output style tag that hides based on `[data-domain]`

## Google
Find the link element and go up a few parent levels and remove the element.

### CODE REVIEW

**Comment by dylanarmstrong** [comment]
Not sure if this is inline with the project or if this would be better as a separate project, since it's not technically a uBlock filter. Open to feedback on that.

**Comment by quenhus** [comment]
Nice, I don't see any problem to merge, even though it's not a uBlock Filter. I would just like to put builds in `dist/userscript/google_duckduckgo/` for consistency.

Btw, nice selector for DDG, I might use it for the uBLock Filter.

Thank you again

**Comment by dylanarmstrong** [comment]
Good call, moved them into subdirectory to match

**Comment by quenhus** [comment]
Thanks, perfect !

**Pull request merged**
