### PR TITLE
add more stackoverflow copycats

### PR DESCRIPTION
**Pull request by Maybach91**
i started creating my [own list](https://gist.github.com/Maybach91/cd8bff4a2930ed2147c853871f23f30d) and found there are some missing in your list as well. but i didn’t filtered by wiki/github copycats, so maybe there are not 100% stackoverflow copycats.

### CODE REVIEW

**Comment by quenhus** [comment]
Hi all,
Thanks a lot for your submission!
As @ZekXtreme stated, I'm not sure every domains are SO mirrors. I'm trying to maintain a block list as tiny as possible, to preserve its relevance.

I'm working to find evidence of "annoyance" for each domain. To do so I'm doing a Google search like `site:DOMAIN` or `How to Linux site:DOMAIN`. I need help to review every domain you suggest.

It is the first time I'm doing this, but to work together on this, I suggest using Cryptpad (Google Sheet alternative) : 

pwd: `quenhus`
https://cryptpad.fr/sheet/#/2/sheet/edit/rH7jEgAXRWKvEbbBkJyKy-Nb/p/

Thanks again!

**Comment by Maybach91** [comment]
> Domain: codingwithfun.com: Could not find concrete evidence of copycat behaviour. Anyone?

They are using the content of w3schools, the only evidence are the broken links at the bottom of each article to a w3school page. 
like:

> That's all there is to it about the difference between Java and PHP. For more Java, PHP learning follow the w3cschool website.

https://codingwithfun.com/article/what-s-the-difference-between-java-and-php/

also different kind of fonts in the sidebar. maybe there is no evidence, but for me the website just look spammy and copied (since the links in the article are all broken) i think its a copy of https://www.w3cschool.cn/minicourse/play/phpcourse (because some links in the article linking to /minicourse/play/phpcourse)

**Comment by quenhus** [comment]
I finished looking for evidence for the **139** domains.

<details> 
  <summary>Here is the result in a BIG table</summary>

Domain | Already in | No evidence found | SEO spam | SO mirror | Evidence
--- | :-: | :-: | :-: | :-: | ---
xspdf.com |   | x |   |   |  
developpaper.com |   |   | x |   | https://developpaper.com/what-is-the-operating-system-linux-operating-system-overview/
tutorialink.com |   |   |   | x | https://linux.tutorialink.com/simulate-right-ctrl-key-using-xdotool-inside-virtual-box/
topcode.in |   |   | x |   | https://topcode.in/download-a-file-from-node-js-server-using-express/
maxinterview.com |   |   |   | x | https://maxinterview.com/code/execute-linux-command-in-python-flask-C83D59373215620/
delicious-insights.com |   | x |   |   | Few Google results
risingstack.com |   | x |   |   | Few Google results
sweetcode.io |   | x |   |   | Few Google results
newdevzone.com |   |   |   | x | https://newdevzone.com/posts/how-to-install-linux-headers-without-an-internet-connection
c-sharpcorner.com |   |   | x |   | 250k Google results
ricardometring.com |   | x |   |   | Few Google results
codeinwp.com |   | x |   |   | Few Google results
javascripttutorial.net |   |   | x |   | Mirrors of docs
learnwithparam.com |   | x |   |   | Real user's content
dirask.com |   |   |   | x | https://dirask.com/questions/JavaScript-how-to-merge-objects-in-array-with-the-same-key-pYEgJp
drempd.com |   | x |   |   | Few Google results
im-coder.com |   |   |   | x | https://im-coder.com/how-to-get-userid-beim-schreiben-von-linux-kernel-modul.html
geekwall.in |   |   | x |   | Redirect to other sites
dzone.com |   |   | x |   | 100k Google results
mastery.games |   | x |   |   |  
mailinglistapi.info |   |   | x |   | Seems broken, but a white table hide hundred of   links
worldgrowthtoday.com |   |   | x |   | https://worldgrowthtoday.com/list-of-best-virtual-machine-software-for-windows/#Gnomes
contactform.dev |   |   |   | x | https://www.contactform.dev/blog/contact-form-with-react-and-php/
emailconverts.info |   |   | x |   | Seems broken, but a white table hide hundred of   links
email-pro.info |   |   | x |   | Seems broken, but a white table hide hundred of   links
qaru.site |   | x |   |   | Seems broken
askdev.info | x |   |   |   |  
programmerz.ru |   | x |   |   | Domain is down
4answered.com |   | x |   |   | Domain is down
qna.one |   | x |   |   | Domain is down
stackovernet.com |   | x |   |   | Domain is down
stackoverrun.com |   | x |   |   | Domain is down
ciupacabra.com |   |   |   | x | Redirects to de-vraag.com, which is a mirror
bildiredi.com |   |   |   | x | Redirects to de-vraag.com, which is a mirror
donolik.com |   |   |   | x | Redirects to de-vraag.com, which is a mirror
pytannie.com |   | x |   |   | Domain is down
sozdizimi.com |   |   |   | x | Redirects to de-vraag.com, which is a mirror
zapytay.com |   |   |   | x | Redirects to de-vraag.com, which is a mirror
while-do.com |   |   |   | x | Redirects to de-vraag.com, which is a mirror
365airsoft.com |   | x |   |   | Domain is down
codeday.me |   | x |   |   | But is considered "malware risk" by a   uBlock filter
issue.life |   | x |   |   | Domain is down
code-adviser.com |   | x |   |   | But is considered "malware risk" by a   uBlock filter
xbuba.com |   | x |   |   | Domain is down
progaide.com |   | x |   |   | Domain is down
stackz.ru |   | x |   |   | Domain is down
it-swarm.net |   |   |   | x | https://www.it-swarm.net/id/dual-boot/dell-xps-13-9360-dual-boot-windows-10-dan-ubuntu-16.04/961095116/amp/
it-swarm.dev |   |   |   | x | https://www.web-dev-qa-db-fra.com/fr/linux/debogage-en-direct-du-noyau-linux-comment-cela-se-fait-et-quels-outils-sont-utilises/971695485/
it-swarm.asia |   |   |   | x | https://www.it-swarm.asia/id/linux/windows-subsystem-linux-buat-vim-menggunakan-clipboard/944423373/
it-swarm.xyz |   |   |   | x | https://it-swarm.xyz/ru/permissions/wordpress-ne-mozhet-zagruzhat-faily/961256598/amp/
bonprog.com |   | x |   |   | Domain is down
bestecode.com |   | x |   |   | Domain is down
progexact.com |   | x |   |   | Domain is down
rstopup.com |   | x |   |   | No mirrors found
profikoder.com |   | x |   |   | Domain is down
src-bin.com |   | x |   |   | No mirrors found
oipapio.com |   | x |   |   | But is considered "malware risk" by a   uBlock filter
quick-geek.github.io |   | x |   |   | Domain is down
icode9.com |   |   | x |   | 375k Google results
develop-bugs.com |   |   |   | x | https://ruby.develop-bugs.com/article/22590425/How+to+make+a+linux+command-line+program+work+in+windows%3F
programqa.com |   | x |   |   | No mirrors found
myht.ru |   | x |   |   | Domain is down
brokencontrollers.com |   | x |   |   | No mirrors found
ffff65535.com |   | x |   |   | Domain is down
900913.ru |   |   | x |   | https://900913.ru/tldr/common/en/pass/
a-scrip.org |   | x |   |   | Domain is down
acnenomor.com |   | x |   |   | No mirrors found
allaskme.com |   | x |   |   | Domain is down
android.bigresource.com |   |   |   | x | Mirror of xda
androiddev.orkitra.com |   | x |   |   | Domain is down
answerhub.com |   | x |   |   | No mirrors found
arrayshift.com |   | x |   |   | Domain is down
ask-coder.com |   | x |   |   | No mirrors found
ask.webatall.com |   | x |   |   | Domain is down
askbot.com |   | x |   |   | No mirrors found
askto.net |   | x |   |   | Domain is down
bhyuu.com |   | x |   |   | No mirrors found, but malware risk
bighow.net |   | x |   |   | Domain is down
cafecoc.com |   | x |   |   | Domain is down
cahoots.com |   | x |   |   | No mirrors found
ciiycode.com |   | x |   |   | Domain is down
code-paper.com |   |   |   | x | https://fr.code-paper.com/shell-bash/examples-view-memory-usage-linux
codeexplain.com |   | x |   |   | Domain is down
codegur.com |   | x |   |   | Domain is down
codeotel.com |   | x |   |   | Domain is down
coderexception.com |   | x |   |   | No mirrors found, but malware risk
coordino.com |   | x |   |   | No mirrors found, but software to mirror SO
efreedom.net |   | x |   |   | Domain is down
exasked.com |   | x |   |   | Domain is down
expertland.net |   | x |   |   | Domain is down
gadgetsytecnologia.com |   | x |   |   | Domain is down
goobbe.com |   | x |   |   | Domain is down
helpmedb.com |   | x |   |   | Domain is down
how-tosolve.com |   | x |   |   | Domain is down
howtobuildsoftware.com |   |   |   | x | Even though domain is down
iditect.com |   |   | x |   | 10k Google results
iswwwup.com |   | x |   |   | No mirrors found, but malware risk
ittone.ma |   |   |   | x | Even though domain is down
jqueryscript.net |   |   | x |   | 20k Google results
levenshteinanswer.com |   | x |   |   | Domain is down
meta.osqa.net |   | x |   |   | Domain is down
newtips.co |   | x |   |   | Domain is down
openoverflow.com |   | x |   |   | No mirrors found, but malware risk
osqa.com |   | x |   |   | Domain is down
osqa.net |   |   | x |   | https://www.osqa.net/how-to-make-2000-dollars-fast/learn/
phpancake.com |   | x |   |   | Domain is down
qathai.com |   | x |   |   | Domain is down
qenabled.com |   | x |   |   | Domain is down
question2answer.com |   | x |   |   | No mirrors found, but software to mirror SO
risposta.org |   | x |   |   | Domain is down
rootbuzz.com |   | x |   |   | Domain is down
seeques.com |   | x |   |   | No mirrors found
shapado.com |   | x |   |   | No mirrors found
sn-gate.com |   | x |   |   | Domain is down
soclone.com |   | x |   |   | Domain is down
solutionscore.com |   | x |   |   | Domain is down
solveseek.com |   | x |   |   | Domain is down
spec-zone.ru |   |   |   | x | Automatic translation (devdocs.io)
stackoverflow.dluat.com |   | x |   |   | Domain is down
stackoverflow.editcode.net | x |   |   |   |  
stackoverflow.hex1.ru |   | x |   |   | Domain is down
stackoverflow.xyz |   | x |   |   | Domain is down
stacksee.lastestapk.com |   | x |   |   | Domain is down
techques.com |   | x |   |   | No mirrors found, but malware risk
tiku.io |   | x |   |   | No mirrors found
tipsforall.xyz |   | x |   |   | Domain is down
w3facility.org |   | x |   |   | No mirrors found
wenda.io |   | x |   |   | Domain is down
wikidevs.com |   | x |   |   | Domain is down
giters.com | x |   |   |   |  
githubmemory. | x |   |   |   |  
bestofreactjs.com | x |   |   |   |  
fantashit.com | x |   |   |   |  
techinplanet.com |   |   |   | x | https://techinplanet.com/is-a-null-check-required-for-array-initialization-in-c-can-array-initialization-in-c-fail/
javascript.tutorialink.com |   |   |   | x | https://javascript.tutorialink.com/extract-the-assignment-of-from-this-expression-with-sonarqube/
codingwithfun.com |   |   | x |   | https://codingwithfun.com/p/data-analysis-of-this-bowl-of-rice-how-to-eat/
lifesaver.codes | x |   |   |   |  
issuecloser.com |   |   |   | x | https://issuecloser.com/blog/launchctl-plist-has-a-stderr-that-talks-about-how-getcwd-operation-not-permitted-so-how-do-i-fix-it
</details>

I am going to update the PR, and merge it in a few days. Please let me know if you see any mistakes.

Thanks to all of you!

**Comment by quenhus** [comment]
For the next time, I just made a Tampermonkey UserScript helper, to help us reviewing big lists of domains. 

Here is the documentation: https://github.com/quenhus/uBlock-Origin-dev-filter/wiki/Helper-to-Review-a-List-of-Domains

Example of the UI: 

Screenshot of how to use the helper

**Pull request merged**
